import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
   <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}>
      <Navbar />
      <AntdRegistry>
        <main className="flex-1 container mx-auto mt-5">{children}</main>
      </AntdRegistry>
      <Footer />
    </body>
  </html>
);

export default RootLayout;